services:
  - type: web
    name: mars-stats
    runtime: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt && python download_dataset.py
    startCommand: python -u server.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: HOST
        value: 0.0.0.0
